### ISSUE TITLE
Fire TV and Kodi Connect impede each other

### ISSUE THREAD

**Issue by DeckardCain2014** [kodi-connect/kodi-connect-addon#10]
As stated in the title, it seems that if linked to the same Echo Dot, the Fire TV and Kodi Connect are not working together. Each Pause and Play command is taken to the Fire TV, not to Kodi.

**Comment by tkislan** [comment]
This is an Amazon issue. Some users reported making this work by disable voice control for Fire TV, if that's something whats viable for you.
