### ISSUE TITLE
AddOn not working in Kodi LibreElEC (official) 8.2.5 -Raspberry Pi

### ISSUE THREAD

**Issue by WilsonBradley** [kodi-connect/kodi-connect-addon#12]
AddOn not working in Kodi LibreElEC (official) 8.2.5 -Raspberry Pi
Fails to install addon as Zip 

addon version 0.1.17

**Comment by WilsonBradley** [comment]
1st time ftp'ed the zip to device locally.
2nd time used wget to get master.zip directly on device directly.

Same issue when installing. Installation failed

**Comment by tkislan** [comment]
You are most likely using incorrect URL to download the addon. You're probably downloading the source code from the Github here.
Download link for the addon is a Dropbox url.
