### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by blacktrails** [kodi-connect/kodi-connect-addon#14]
I have installed the correct repository and addon, and entered my credentials, but every time I try to link my echo with the device Amazon returns "Sorry, we could not find any devices to link." I had one of my Kodis connected but I can get any others to work.

**Comment by blacktrails** [comment]
I’ve got it working on fire tv again. There’s a new update 0.01.22 or something like that. You’ll also need to request access again, but he has made it automated so it’s super quick. Go back and re read the updated tutorials. Now if I could just get it working on Xbox one I’d be happy

**Comment by Maximus1** [comment]
i have installed v22 but nothing happens. kodi tells me kodi connect is connected but on the alexa site my kodi is not found.

**Comment by blacktrails** [comment]
Hmmmm. Have you tried deleting it out of the kodiconnect site and get a new secret?

**Comment by Maximus1** [comment]
i´ll try later. my wife is watching top gear. :-)
