### ISSUE TITLE
We were unable to link Kodi at this time

### ISSUE THREAD

**Issue by nex6** [kodi-connect/kodi-connect-addon#17]
Getting an error when linking the skill with my Kodi Connect device, "We were unable to link Kodi at this time".

Have installed the Kodi addon, Kodi states that Kodi Connect is connected after start but when trying to link the skill in Alexa, I am constantly getting this error. Have tried to delete my device and created a new secret, have tried enabling the skill on different devices but nothing works... Have set my Amazon account to US since the skill is "devUS" version. I am not connecting from US though, can that be the issue? What am I doing wrong?

**Comment by tkislan** [comment]
Please follow this issue:
https://github.com/kodi-connect/kodi-alexa-video/issues/65
