### ISSUE TITLE
Any idea --> Currently there are no connected devices.

### ISSUE THREAD

**Issue by SmilyHM** [kodi-connect/kodi-connect-addon#20]
Hi everyone,

I don't know the correct button-names (my language is GER):

1. I can start "connect devices" or "connect a different device"
2. It shows my KODI with name "OSMC-Wohnzimmer" (RPI2 running OSMC latest build (17.n))
3. select "next"
4. It shows all my echo-devices (8).
5. Select "Wohnzimmer" (the device in the livingroom)
6. select "connect devices"
7. It shows "currently there are no connected devices!

It's an endless loop...  :(

Any ideas? Of course I found the issue "Registration SetUp within Alexa App does not work #15" wich is marked as "closed" and "duplicate" --> but where is the dublicate? I read all Issues (open and closed) but couldn't find a sollution for me (?). (I've got no FireTV! - this problem can be ruled out before)

Thanks and best regards from GER
Sascha

**Comment by mikehobin** [comment]
I too have this same issue, Kodi 18.0 (LibreElec specifically) and tried multiple versions of the Plugin)

**Comment by SmilyHM** [comment]
For me, the issue could be closed. I can't say how many time i've done the steps above, but now it works... Don't know why. --> It still shows "currently there are no connected devices!", but now works!

@mikehobin just to be sure: do you use portforwarding? i'm using port 2340 (external) to port 8080 (internal). 8080 = the port set up in kodi

**Comment by mikehobin** [comment]
No, no port forwarding setup. 

I'll spend some more time later today trying to figure it out, but just thought I would put it out there that this "issue" wasn't just you.
