### ISSUE TITLE
{"error":"Vendor ID not found"}

### ISSUE THREAD

**Issue by noodles1984** [kodi-connect/kodi-connect-addon#29]
Hi,

I'm getting this error message when returning to kodi connect page after logging in to my amazon account.

Did anyone have the same issue?

**Comment by tkislan** [comment]
Hey,
yes, some people had the issue with this before, but I can't remember what the solution was
Could you try to log into https://developer.amazon.com/alexa/console/ask# page, maybe it creates vendor ID automatically once you log in there

**Comment by noodles1984** [comment]
Thanks for the quick reply. I've tried it again after several times and now it worked. I don't even know why. 
Great skill! Thank you very much for your work!
