### ISSUE TITLE
connecting/disconnecting

### ISSUE THREAD

**Issue by steve55792** [kodi-connect/kodi-connect-addon#3]
Hi, I added the addon to kodi and it says  its connected and few seconds later it says disconnected. What did i do wrong?

                                                                                               Steve

**Comment by tkislan** [comment]
This is caused by incorrect credentials in the addon settings

**Comment by steve55792** [comment]
Like if put the secret key in wrong?
--------------------------------------------
On Tue, 7/10/18, Tomas Kislan <notifications@github.com> wrote:

 Subject: Re: [kodi-connect/kodi-connect-addon] connecting/disconnecting (#3)
 To: "kodi-connect/kodi-connect-addon" <kodi-connect-addon@noreply.github.com>
 Cc: "steve55792" <steve55792@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, July 10, 2018, 2:05 AM
 
 This is caused by incorrect
 credentials in the addon settings
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by tkislan** [comment]
Yes exactly
