### ISSUE TITLE
Can't find Skill at Amazon.es

### ISSUE THREAD

**Issue by smontys** [kodi-connect/kodi-connect-addon#30]
Hi, Awesome job! 
Should it be available to Spain at any time?
Any plans for music integration?

Regards.

**Comment by tkislan** [comment]
Amazon refused to have the skill certified. So no time window when it might actually be fully functional ...

**Comment by smontys** [comment]
Thanks for your comment. What about the beta version?

**Comment by tkislan** [comment]
That is not a viable long term solution, as it lasts only for 30 days, and was really buggy.

**Comment by smontys** [comment]
Apologizes, I was talking about skill creation from kodiconnect. I'm redoing that part and I'm not able to do that step: after arn input, lambda function already created, I'm getting 504 Gateway timeout.
Ok, I'll ask for help at Discord.

**Comment by tkislan** [comment]
Oh. Well I don't know why that is happening .. I'll improve some logging around that, so that I can investigate more

**Comment by smontys** [comment]
Thanks Tomas, I'll start again from scratch.

**Comment by smontys** [comment]
One question, is it possible that 'Alexa Smart Home' trigger has changed to 'Alexa skills kit'? Because I can't find it.

**Comment by smontys** [comment]
Ok, solved. My mistake not to select eu-west-1 (Ireland) for Spanish. An the skill appears at 'My kills'), Developer part.
Many thanks Tomas, for your work and support, and sorry for inconvenience. Going to playing with it!
Best regards.
