### ISSUE TITLE
{"error":"Skill doesn't exist"}

### ISSUE THREAD

**Issue by ramante** [kodi-connect/kodi-connect-addon#31]
Hi There, 

When I press "Link Lambda" I got the {"error":"Skill doesn't exist"} error message. I tried to redo the process several time but alwaysgot the same message. Someone had the same issue?

**Comment by tkislan** [comment]
What region did you create your lambda function in?

**Comment by ramante** [comment]
Hi Tomas, thank you so much for your prompt answer. 
I tried first time using sa-east-1 and, then, I tried us-west-1.
Should I try another one?
Regards,
Rogerio

**Comment by tkislan** [comment]
None of those are supported .. please read the tutorial .. there is a table which describes what region to choose

**Comment by ramante** [comment]
Ok, I will try it right now.
Thanks again!

**Comment by ramante** [comment]
Hi, just to let you know, WORKED!!! Thanks again.

**Comment by ramante** [comment]
Hi Tomas, could you tell if there is a list of Alexa commands to use on Kodi? I didn't find it.
Regards

**Comment by tkislan** [comment]
https://kodi-connect.github.io
its literally the first section
