### ISSUE TITLE
Kodi Connect add-on 0.2.4 not working with KODI 19

### ISSUE THREAD

**Issue by rosenzzzz** [kodi-connect/kodi-connect-addon#33]
When installing the Kodi Connect add-on 0.2.4 on KODI 19 on an Android box, I get an error that Python 2.14 is not installed. In searching for a fix, I learned that KODI 19 uses Python 3. Is there a fix for this or do I need I wait until you update the add-on? If I need to wait, do you have an estimate on how long?
Thank you for your amazing add-on. Excited to finally try it.

**Comment by tkislan** [comment]
Closing in favor of https://github.com/kodi-connect/kodi-connect-addon/issues/35
