### ISSUE TITLE
Failed to login in alexa

### ISSUE THREAD

**Issue by DrMacabre** [kodi-connect/kodi-connect-addon#36]
Hello, i messed up with my install, removed both of my instances on your site and readded them with new secret phrase but now I’m unable to use the skill and when i try to readd the skill in alexa, it failed to login, my credentials are good, i use them on a different page. Any idea ?

**Comment by tkislan** [comment]
On which page can you not login? Amazon?

**Comment by DrMacabre** [comment]
First i deleted my instances on your page by mistake so i readded them, both said connected but they were unresponsive with alexa, actually the skill was responding but kodi wasn’t executing the order so i thought may be i had to relink the skill and everything so i went on the alexa app and removed the skill and reinstalled it, that’s where it require to log on your page and where my credentials are rejected with a failed to login message.

**Comment by tkislan** [comment]
If you can login to https://kodiconnect.kislan.sk without Alexa linking, when the actual skill linking occurs, it shouldn't even request to login .. you should already be logged in
Are you doing this through mobile phone or desktop browser?

**Comment by DrMacabre** [comment]
I’m on my ipad, i suspect alexa app to open the link with another browser than the one I’m usually using. Probably safari instead of firefox. I will do it on my computer just to be sure.

**Comment by tkislan** [comment]
Yes, I think there were some issues in the past, where it wasn't really working with the mobile app

Also, since you've re-added the devices, you will also need to run the discovery again

**Comment by DrMacabre** [comment]
OK it's done, everything works as usual except i have twice each device in alexa, had to figure which one was the right one. Do you know if there is a way to delete the unused device ? i relinked the skill and that's when it doubled my kodi devices.

**Comment by tkislan** [comment]
You should be able to delete/remove devices in Alexa app

**Comment by DrMacabre** [comment]
Yes of course, didn’t think about directly deleting the devices 😪. Thank you for your help.
