### ISSUE TITLE
"Kodi Connect Nothing Found"

### ISSUE THREAD

**Issue by jgladwill** [kodi-connect/kodi-connect-addon#8]
I had to disable Fire TV skill to get Kodi Video skill to manage videos. Everything seems to be connected now, except it's not fetching any of the actual data from Kodi, ie ...

Me: "Alexa, show me action movies"
Alexa: "Getting action movies from Kodi video ..."
Kodi: (i) **Kodi Connect** Nothing Found

I also attempted a few other examples in the documents and keep getting the same results

**Devices / Software**
- Alexa Echo Plus Model ZE39KL (software version 606753920)
- Firestick 
- Firestick: Kodi Krypton (17.6)
- Firestick: Kodi Limitless (Lite)
- Firestick: Kodi Connect 0.1.17

**Comment by tkislan** [comment]
Kodi connect addon only queries Kodi's Video library. It does not look for files on filesystem, nor does it work with any 3rd party addons.
